### ISSUE TITLE
ServletException: MessageBodyWriter not found for media type=application/yaml

### ISSUE THREAD

**Issue by ptuckey** [fehguy/swagger-editor-backend#1]
Installing and starting up works for me, but when I access "0.0.0.0:8080" with my browser, the server throws the following exception:

javax.servlet.ServletException: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=application/yaml, type=class io.swagger.inflector.examples.models.StringExample, genericType=class io.swagger.inflector.examples.models.StringExample.

Full stack trace:
http://pastebin.com/facfmZeL

Apache Maven 3.3.1
Java 1.7.0_71

**Comment by fehguy** [comment]
Sorry that took so long, I've updated to release dependencies.  Can you please test again, @ptuckey ?

**Comment by ptuckey** [comment]
Working now, thanks!
